### ISSUE TITLE
Document Resume Screener

### ISSUE THREAD

**Issue by vish-rt** [tcet-opensource/documentation#33]

**Comment by prathikshetty2002** [comment]
These things have to be documented 

**Phase 1**
- [ ] Resume screener general guide
- [ ] upload resume (Thakur format) about this format
- [ ] How we generate recommendations (skills & courses)
- [ ] How we calculate user resume skill score & overall score
- [ ] Process to generate ATS-compatible suggestions

>**Note** 
>The functionalities are currently under implementation we have created a reference where all these are already done now migration is under process.

**Comment by prathikshetty2002** [comment]
> Can you provide me references for these? So that i can understand and document it accordingly.  

Hi Arya i will update this with technical document list pls ignore the above one
